# Generated by Django 4.2.16 on 2024-11-19 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instruments',
            new_name='Instrument',
        ),
        migrations.RenameField(
            model_name='musician',
            old_name='instruments',
            new_name='instrument',
        ),
    ]
